## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-clipboard-pipes-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Clipboard Pipes
description: Workflow to apply bash-like snippets to the content of the clipboard, replacing it.
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-clipboard-pipes-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox